### ISSUE TITLE
Wrong download link in version file 2.9.2a

### ISSUE THREAD

**Issue by AlfredBroda** [CaymonJoestar/Diable-Avionics#1]
The version file as of 2.9.2a is still pointing at "https://github.com/CaymonJoestar/Diable-Avionics/releases/download/DiableV.2.9.0/Diable-Avionics-v2.9.0.zip" which makes mod managers fail to update this mod.

**Comment by CaymonJoestar** [comment]
Fixed, should work with the mod managers now hopefully
